import React from 'react';
import { Grid, Row, Col } from 'react-bootstrap';

export default function Science() {
  return (
    <Grid fluid>
      <h1>Scientific References</h1>
      <Row>
        <Col lg={6}>
          <h2>Statistically Downscaled Climate Scenarios</h2>
          <p><strong>Bürger, G.</strong>,<strong> T.Q. Murdock</strong>, <strong>A.T. Werner</strong>, <strong>S.R. Sobie</strong>,&nbsp;and <strong>A.J. Cannon</strong>, 2012:&nbsp;<a href="http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-11-00408.1" class="ext" target="_blank" rel="noopener noreferrer">Downscaling extremes - an intercomparison of multiple statistical methods for present climate<span class="ext" aria-label="(link is external)"></span></a>. <em>Journal of Climate</em>, <strong>25</strong>,&nbsp;4366–4388. doi:10.1175/JCLI-D-11-00408.1.</p>
          <p><strong>Bürger, G.</strong>, <strong>S.R. Sobie</strong>, <strong>A.J. Cannon</strong>, <strong>A.T. Werner</strong>,&nbsp;and <strong>T.Q. Murdock</strong>, 2013<span>:</span> <a href="http://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-12-00249.1" class="ext" target="_blank" rel="noopener noreferrer">Downscaling extremes - an intercomparison of multiple methods for future climate<span class="ext" aria-label="(link is external)"></span></a>.<em> Journal of Climate</em>, <strong>26</strong>,&nbsp;3429-3449. doi:10.1175/JCLI-D-12-00249.1.</p>
          <p><strong>Cannon, A.J.</strong>, 2015: Selecting GCM scenarios that span the range of changes in a multimodel ensemble: application to CMIP5 climate extremes indices.<em> Journal of Climate</em>, <strong>28</strong>(3): 1260-1267. doi:10.1175/JCLI-D-14-00636.1</p>
          <p><strong>Cannon, A.J.</strong>,<strong> S.R. Sobie</strong>, and <strong>T.Q. Murdock</strong>, 2015: <a href="https://journals.ametsoc.org/doi/abs/10.1175/JCLI-D-14-00754.1" class="ext" target="_blank" rel="noopener noreferrer">Precipitation by Quantile Mapping: How Well Do Methods Preserve Changes in Quantiles and Extremes?<span class="ext" aria-label="(link is external)"></span></a> <em>Journal of Climate</em>, <strong>28</strong>(17), 6938-6959, doi:10.1175/JCLI-D-14-00754.1.</p>
          <p>Giorgi, F. and Francisco, R., 2000: Evaluating uncertainties in the prediction of regional climate change. <em>Geophysical Research Letters</em>, <strong>27</strong>(9), 1295-1298.</p>
          <p>Gudmundsson, L., J. B. Bremnes, J. E. Haugen, and T. Engen-Skaugen, 2012: <a href="http://www.hydrol-earth-syst-sci.net/16/3383/2012/hess-16-3383-2012.html" class="ext" target="_blank" rel="noopener noreferrer">Technical Note: Downscaling RCM precipitation to the station scale using statistical transformations - a comparison of methods<span class="ext" aria-label="(link is external)"></span></a>. <em>Hydrology and Earth System Sciences</em>, <strong>16</strong>, 3383–3390, doi:10.5194/hess-16-3383-2012.</p>
          <p><strong>Hiebert, J.</strong>, <strong>A. Cannon</strong>, <strong>A. Schoeneberg</strong>,<strong> S. Sobie</strong>, and <strong>T. Murdock</strong>, 2018: <a href="http://joss.theoj.org/papers/87c76a9d8f39f0dafbda6388b82f5cf0" class="ext" target="_blank" rel="noopener noreferrer">ClimDown: Climate Downscaling in R<span class="ext" aria-label="(link is external)"></span></a>. <em>The Journal of Open Source Software</em>, <strong>3</strong>(22), 360, doi:10.21105/joss.00360.</p>
          <p>Hopkinson, R.F., D.W. McKenney, E.J. Milewska, M.F. Hutchinson, P. Papadopol, and&nbsp;L.A. Vincent, 2011: <a href="http://journals.ametsoc.org/doi/abs/10.1175/2011JAMC2684.1" class="ext" target="_blank" rel="noopener noreferrer">Impact of Aligning Climatological Day on Gridding Daily Maximum–Minimum Temperature and Precipitation over Canada<span class="ext" aria-label="(link is external)"></span></a>.<em> Journal of Applied Meteorology and Climatology</em>, <strong>50</strong>,&nbsp;1654–1665. doi:10.1175/2011JAMC2684.1.</p>
          <p>Hunter, R. D., and R. K. Meentemeyer, 2005: <a href="http://journals.ametsoc.org/doi/abs/10.1175/JAM2295.1" class="ext" target="_blank" rel="noopener noreferrer">Climatologically Aided Mapping of Daily Precipitation and Temperature<span class="ext" aria-label="(link is external)"></span></a>. <em>Journal of Applied Meteorology</em>, <strong>44</strong>, 1501–1510, doi:10.1175/JAM2295.1.</p>
          <p>Eum, H.-I., Dibike, Y., Prowse, T. and Bonsal, B., 2014, Inter-comparison of high-resolution gridded climate data sets and their implication on hydrological model simulation over the Athabasca Watershed, <em>Canada. Hydrol. Process.</em>, <strong>28</strong>, 4250–4271. doi: 10.1002/hyp.10236.</p>
          <p>Li, C., Y. Fang, K. Calderia, X. Zhang, N.S. Diffenbaugh, and A.M. Michalak, 2018: <a href="https://www.nature.com/articles/s41598-018-19288-z" class="ext" target="_blank" rel="noopener noreferrer">Widespread persistent changes to temperature extremes occurred earlier than predicted<span class="ext" aria-label="(link is external)"></span></a>. <em>Nature Scientific Reports</em>, <strong>8</strong>, 1007, doi:10.1038/s41598-018-19288-z&nbsp;&nbsp;</p>
          <p>Maurer, E.P., and H.G. Hidalgo, 2008: <a href="http://www.hydrol-earth-syst-sci.net/12/551/2008/hess-12-551-2008.html" class="ext" target="_blank" rel="noopener noreferrer">Utility of daily vs. monthly large-scale climate data: an intercomparison of two statistical downscaling methods<span class="ext" aria-label="(link is external)"></span></a>. <em>Hydrology and Earth System Sciences</em>, <strong>12</strong>,&nbsp;2,&nbsp;551-563. doi:10.5194/hess-12-551-2008.</p>
          <p>Maurer, E., H. Hidalgo, T. Das, M. Dettinger, and D. Cayan, 2010: <a href="http://www.hydrol-earth-syst-sci.net/14/1125/2010/hess-14-1125-2010.html" class="ext" target="_blank" rel="noopener noreferrer">The utility of daily large-scale climate data in the assessment of climate change impacts on daily streamflow in California<span class="ext" aria-label="(link is external)"></span></a>. <em>Hydrology and Earth System Sciences</em>, <strong>14</strong>, 6, 1125–1138,&nbsp;doi:10.5194/hess-14-1125-2010.</p>
          <p>McKenney, D.W., M.F. Hutchinson, P. Papadopol, K. Lawrence, J. Pedlar, K. Campbell, E. Milewska, R. Hopkinson, D. Price, and T. Owen, 2011: <a href="http://journals.ametsoc.org/doi/abs/10.1175/2011BAMS3132.1" class="ext" target="_blank" rel="noopener noreferrer">Customized spatial climate models for North America<span class="ext" aria-label="(link is external)"></span></a>. <em>Bulletin of the American Meteorological Society</em>, <strong>92</strong>,&nbsp;12,&nbsp;1611-1622. doi:10.1175/2011BAMS3132.1.</p>
          <p>Meinshausen, M., et al., 2011: The RCP greenhouse gas concentrations and their extensions from 1765 to 2300. <em>Climatic Change</em>, <strong>109</strong>(1-2), 213-241.</p>
          <p><strong>Sobie, S.R.</strong>, and <strong>T.Q. Murdock</strong>, 2017: <a href="https://journals.ametsoc.org/doi/abs/10.1175/JAMC-D-16-0287.1" class="ext" target="_blank" rel="noopener noreferrer">High-Resolution Statistical Downscaling in Southwestern British Columbia<span class="ext" aria-label="(link is external)"></span></a>.<em> Journal of Applied Meteorology and Climatology</em>, <strong>56</strong>(6), 1625–1641, doi:10.1175/JAMC-D-16-0287.1.</p>
          <p>Taylor, K.E., R.J. Stouffer, and&nbsp;G.A. Meehl, 2012:<a href="http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-11-00094.1" class="ext" target="_blank" rel="noopener noreferrer"> An Overview of CMIP5 and the Experiment Design<span class="ext" aria-label="(link is external)"></span></a>. <em>Bulletin of the American Meteorological Society</em>, <strong>93</strong>,&nbsp;485–498. doi: 10.1175/BAMS-D-11-00094.1.</p>
          <p><strong>Werner, A.T.</strong>, 2011: <em><a href="http://www.pacificclimate.org/sites/default/files/publications/Werner.HydroModelling.FinalReport1.Apr2011.pdf" target="_blank">BCSD downscaled transient climate projections for eight select GCMs over British Columbia</a>, Canada</em>. Pacific Climate Impacts Consortium, University of Victoria, Victoria, BC, 63 pp.</p>
          <p><strong>Werner, A.T.</strong> and <strong>A.J. Cannon</strong>, 2015: Hydrologic extremes – an intercomparison of multiple gridded statistical downscaling methods. <em>Hydrology and Earth System Sciences Discussion</em>, <strong>12</strong>, 6179-6239, doi:10.5194/hessd-12-6179-2015.</p>
          <p>Wood, A.W., L.R Leung, V. Sridhar, and D.P. Lettenmaier, 2004: <a href="http://link.springer.com/article/10.1023%2FB%3ACLIM.0000013685.99609.9e" class="ext" target="_blank" rel="noopener noreferrer">Hydrologic implications of dynamical and statistical approaches to downscaling climate model outputs<span class="ext" aria-label="(link is external)"></span></a>. <em>Climatic Change</em>, <strong>62</strong>,&nbsp;189–216, doi:10.1023/B:CLIM.0000013685.99609.9e.</p>

        </Col>
      </Row>
    </Grid>
  );
}
