name: Node CI

on: push

jobs:
  node-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node.js Test Suite
        run: |
          npm install
          npm test
